name: Repo Info with context

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
            
      - uses: actions/checkout@v3

      - name: show branch info and GitHub context
        run: |
          echo Info follows on ${{ github.repository }}
          echo Default branch is "main"
          echo Size of repository is `du -hs ${{ github.workspace }}`
          
      - name: Dump job context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
                
   # add your jobs here     
