name: Repo Info with context

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
            
      - uses: actions/checkout@v3
          
      - name: Show repo infot
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo Info follows on ${{ github.repository }}
          echo Size of repository is `du -hs ${{ github.workspace }}`
          echo "$GITHUB_CONTEXT"
                
   # add your jobs here     
