name: Repo Info with context

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
            
      - uses: actions/checkout@v3
          
      - name: Show repo info
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo Repository is ${{ github.repository }}
          echo Default branch is main
          echo Size of repository is `du -hs ${{ github.workspace }}`
          echo Context dump follows:
          echo "$GITHUB_CONTEXT"
                
   # add your jobs here     
